"""indexes for person attendance history and per-session recognition logs

Revision ID: ab8b30513d68
Revises: ca08227f1e27
Create Date: 2026-08-02 12:04:15.880184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8b30513d68'
down_revision = 'ca08227f1e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_person_marked', ['person_id', 'marked_at'], unique=False)

    with op.batch_alter_table('recognition_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recognition_logs_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognition_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recognition_logs_session_id'))

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_person_marked')

    # ### end Alembic commands ###
