"""add person_source_images table

Revision ID: ac0d76fbe1b5
Revises: f797c69e0baf
Create Date: 2026-08-02 15:51:57.016624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0d76fbe1b5'
down_revision = 'f797c69e0baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_source_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_source_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_source_images_person_id'), ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_source_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_source_images_person_id'))

    op.drop_table('person_source_images')
    # ### end Alembic commands ###
