"""add department and year to person

Revision ID: f797c69e0baf
Revises: ab8b30513d68
Create Date: 2026-08-02 15:41:28.943012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f797c69e0baf'
down_revision = 'ab8b30513d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_persons_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_year'))
        batch_op.drop_index(batch_op.f('ix_persons_department'))
        batch_op.drop_column('year')
        batch_op.drop_column('department')

    # ### end Alembic commands ###
